site_name: GHDDI nCov Info Sharing Portal
site_author: David Leon (Dawei Leng)
docs_dir: docs

markdown_extensions:
    - pymdownx.arithmatex

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
    - Home: index.md
    - nCov:
      - Experiment Data: CoV_Experiment_Data.md
      - Structural Modeling: nCov_Structural_Modeling.md
      - Research Progress: research_progress.md
    - History: history.md


theme: readthedocs    
    
