site_name: Targeting 2019-nCoV Portal
site_author: David Leon (Dawei Leng)
docs_dir: docs

markdown_extensions:
    - pymdownx.arithmatex

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
    - Home: index.md
    - Data Download:
      - Experimental Data: CoV_Experiment_Data.md
      - Structure Modeling: nCov_Structural_Modeling.md
      - Research Update: research_progress.md
    - Community Discussion: contact_us.md
    - History: history.md


theme: readthedocs    
    
